services:
  api:
    image: ghcr.io/jeonghwan-hwang/project-a:git-2b273987e10c4a4db2b8b1a71edbb42cb8920bb9
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      company.project: project-a
      company.service: api
      company.owner: jeonghwan-hwang
