services:
  api:
    image: ghcr.io/jeonghwan-hwang/project-a:git-671c909abec78c0b3c96e01ece51b61bc5f25354
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      company.project: project-a
      company.service: api
      company.owner: jeonghwan-hwang
